### ISSUE TITLE
Stopped working after latest updated due to audiocontrol2sio

### ISSUE THREAD

**Issue by borky** [willholdoway/hifiberry#15]
After latest update the component stopped working and throws following error in the log:
**_Error occurred loading configuration flow for integration hifiberry: No module named 'pyhifiberry.audiocontrol2sio'._**
I tried reinstalling it but the problem persists. Can you please take a look or provide a solution on how to fix this error?

**Comment by techcenter68** [comment]
I have the same issue... 

Logger: homeassistant.config_entries
Source: config_entries.py:745
First occurred: 06:14:11 (15 occurrences)
Last logged: 08:18:25

Error occurred loading configuration flow for integration hifiberry: No module named 'pyhifiberry.audiocontrol2sio'

**Comment by borky** [comment]
after latest update i get the following exception when i try to add the integration from scratch: 
_**2022-04-06 08:18:10 ERROR (MainThread) [custom_components.hifiberry.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/hifiberry/config_flow.py", line 69, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/hifiberry/config_flow.py", line 23, in validate_input
    await Audiocontrol2SIO.connect(host=data["host"], port=data["port"])
  File "/usr/local/lib/python3.9/site-packages/pyhifiberry/audiocontrol2sio.py", line 38, in connect
    await sio.connect(f'http://{host}:{port}', wait_timeout=wait_timeout)
TypeError: connect() got an unexpected keyword argument 'wait_timeout'**_

**Comment by schnabel** [comment]
Hi @borky @techcenter68 please have a look [here](https://github.com/willholdoway/hifiberry/issues/16).

**Comment by borky** [comment]
it is working now. thanks for the fast fix!
