### ISSUE TITLE
Please help - I don't know how to add HiFi Berry via HACS

### ISSUE THREAD

**Issue by jaku2019** [willholdoway/hifiberry#22]
Hello,

I’m using Digi+ card on RPi 0W with HiFiBerryOS 20201213 installed.

I wanted to install this integration via HACS.
Everything went successfuly, but now I’m struggling with configuiring that.

Should I paste HiFiBarry’s IP in the “host” section?
What should I type in authtoken field?

Regards,
Jakub
![HifiB](https://user-images.githubusercontent.com/55255300/184553246-d19c906c-e7ec-49f9-82b3-c389d5d535dc.png)

**Comment by dmnc-net** [comment]
Yes, put HiFiBerry ip in the host field and leave the authtoken blank (or if there's any then set the value from HiFiBery: `cat /etc/audiocontrol2.conf|grep authtoken`). You can try to connect to API manually with http://your-hifiberry-ip:81/api/player/status

I think that problem is somewhere else, after some update I can't connect anymore too.

**Comment by jaku2019** [comment]
> Yes, put HiFiBerry ip in the host field and leave the authtoken blank (or if there's any then set the value from HiFiBery: `cat /etc/audiocontrol2.conf|grep authtoken`). You can try to connect to API manually with http://your-hifiberry-ip:81/api/player/status
> 
> I think that problem is somewhere else, after some update I can't connect anymore too.

Thank you for the answer.

Unfortunetly, after typing proper information, I can't connect to my HiFiberry.

Do you know any way to retrieve older (the working one) version on this plugin?

Regards
Jakub

PS. I'm using HiFiberryOS on the Pi 0 and I want to add Spotify connect to it. I wanted to use Home assistant as a workaround (Spotify->Home Assistant->HiFiberry). Do you think that it's going to work?

**Comment by willholdoway** [comment]
Hi Jaksub, I think there's misunderstanding. This is just a control plugin so won't add any features to your HiFiberry. If you have HiFiBerry installed on your Pi Zero then it should work with Spotify Connect out of the box

**Comment by dmnc-net** [comment]
@willholdoway but both of us were describing the HiFiBerry HA integration installed with HACS. It was working, then went broke.
