### ISSUE TITLE
Failed to set up integration after has 2023.5 update

### ISSUE THREAD

**Issue by MrRodz** [willholdoway/hifiberry#26]
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/hifiberry/__init__.py:31 
Integration: HiFiBerry (documentation) 
First occurred: 13:38:56 (2 occurrences) 
Last logged: 13:49:25

Error setting up entry 192.168.10.42 for hifiberry
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hifiberry/__init__.py", line 31, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

I get this error on the intergration

Regards

**Comment by KocproZ** [comment]
It's already addressed in #25, it just has to be merged
