### ISSUE TITLE
custom_component using deprecated features (as per 2025.01)

### ISSUE THREAD

**Issue by KomtGoed** [willholdoway/hifiberry#30]
Hi,

Was checking my HA logs and noted the following message:

`Entity None (<class 'custom_components.hifiberry.media_player.HifiberryMediaPlayer'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.PAUSE|VOLUME_SET|VOLUME_MUTE|PREVIOUS_TRACK|NEXT_TRACK|TURN_OFF|VOLUME_STEP|STOP|PLAY: 21821>, please report it to the author of the 'hifiberry' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation`

Is this something easy to fix?

**Comment by willholdoway** [comment]
done

**Comment by KomtGoed** [comment]
That was quick, thanks a lot! Just downloaded and can confirm that message has disappeared.
