### ISSUE TITLE
Changes in Home Assistant Core 2021.3

### ISSUE THREAD

**Issue by TheGroundZero** [willholdoway/hifiberry#4]
```
No 'version' key in the manifest file for custom integration 'hifiberry'.
This will not be allowed in a future version of Home Assistant.
Please report this to the maintainer of 'hifiberry' 
```

See https://www.home-assistant.io/blog/2021/03/03/release-20213#breaking-changes
Under `Custom integrations: Version warning`

**Comment by AcidSleeper** [comment]
@willholdoway add the code below to manifest.json to solve the warning

"version": "0.0.1"
