### ISSUE TITLE
Cannot add integration

### ISSUE THREAD

**Issue by ryanxav** [willholdoway/hifiberry#7]
I've upgraded to latest version and can't add HifiBerry integration.

Browsing to 'Add Integration', I search for HifiBerry and click it. The list of available integrations reloads, nothing happens.

The log file records:

ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration hifiberry: cannot import name 'FlowResult' from 'homeassistant.data_entry_flow' (/srv/homeassistant/lib/python3.8/site-packages/homeassistant/data_entry_flow.py)

Any help greatly appreciated

**Comment by willholdoway** [comment]
@dgomes created the flow. Are you able to troubleshoot this @dgomes ?

**Comment by dgomes** [comment]
You need to upgrade HA to at least version 2021.5.1

**Comment by ryanxav** [comment]
Thanks guys!
